import { Schema, model, type Types } from 'mongoose';

export interface IAdmin { username: string; passwordHash: string }
export interface ISession { adminId: Types.ObjectId; tokenHash: string; expiresAt: Date }
export interface IProfile { name: string; username: string; role: string; location: string; status: string; heroGreeting: string; heroDescription: string[]; about: string; profileImage?: string; profileImagePublicId?: string; email: string; github: string; instagram: string; cvUrl?: string; cvPublicId?: string }
export interface IProject { name: string; slug: string; shortDescription: string; overview?: string; problem?: string; solution?: string; challenges?: string; result?: string; features: string[]; thumbnail?: string; thumbnailPublicId?: string; gallery: string[]; galleryPublicIds: string[]; stack: string[]; status: 'deployed' | 'development' | 'archived'; githubUrl?: string; liveUrl?: string; featured: boolean; year?: number; displayOrder: number }
export interface ISkill { name: string; category: 'frontend' | 'backend' | 'database' | 'tools' | 'language'; icon?: string; displayOrder: number; visible: boolean }
export interface IExperience { company: string; role: string; companyLogo?: string; companyLogoPublicId?: string; startDate: Date; endDate?: Date; current: boolean; description: string; technologies: string[]; displayOrder: number }
export interface ICertificate { name: string; issuer: string; issueDate: Date; image?: string; imagePublicId?: string; credentialId?: string; credentialUrl?: string; displayOrder: number }
export interface IPersonalItem { category: 'hobbies' | 'currently' | 'favorites' | 'dream-setup' | 'dream-garage' | 'dream-home' | 'career-goal' | 'life-goal' | 'bucket-list' | 'fun-facts' | 'personal-quote'; title: string; description?: string; image?: string; imagePublicId?: string; imageAlt?: string; label?: string; icon?: string; status?: string; url?: string; completed: boolean; size: 'small' | 'wide' | 'tall' | 'large'; displayMode: 'visual' | 'text'; order: number; visible: boolean }
export interface ISiteSettings { siteTitle: string; terminalUsername: string; terminalHostname: string; systemOS: string; footerQuote: string; availabilityStatus: string; bootEnabled: boolean; sideStreamEnabled: boolean; crtEnabled: boolean }
export interface IMessage { name: string; email: string; message: string; read: boolean }

const options = { timestamps: true } as const;
export const Admin = model<IAdmin>('Admin', new Schema<IAdmin>({ username: { type: String, required: true, unique: true, trim: true }, passwordHash: { type: String, required: true } }, options));
const sessionSchema = new Schema<ISession>({ adminId: { type: Schema.Types.ObjectId, ref: 'Admin', required: true }, tokenHash: { type: String, required: true, unique: true }, expiresAt: { type: Date, required: true, index: { expires: 0 } } });
export const Session = model<ISession>('Session', sessionSchema);
export const Profile = model<IProfile>('Profile', new Schema<IProfile>({ name: { type: String, required: true }, username: { type: String, required: true }, role: { type: String, required: true }, location: { type: String, required: true }, status: { type: String, required: true }, heroGreeting: { type: String, required: true }, heroDescription: { type: [String], default: [] }, about: { type: String, required: true }, profileImage: String, profileImagePublicId: String, email: { type: String, required: true }, github: String, instagram: String, cvUrl: String, cvPublicId: String }, options));
export const Project = model<IProject>('Project', new Schema<IProject>({ name: { type: String, required: true }, slug: { type: String, required: true, unique: true, lowercase: true }, shortDescription: { type: String, required: true }, overview: String, problem: String, solution: String, challenges: String, result: String, features: { type: [String], default: [] }, thumbnail: String, thumbnailPublicId: String, gallery: { type: [String], default: [] }, galleryPublicIds: { type: [String], default: [] }, stack: { type: [String], default: [] }, status: { type: String, enum: ['deployed', 'development', 'archived'], required: true }, githubUrl: String, liveUrl: String, featured: { type: Boolean, default: false }, year: Number, displayOrder: { type: Number, default: 0 } }, options));
export const Skill = model<ISkill>('Skill', new Schema<ISkill>({ name: { type: String, required: true }, category: { type: String, enum: ['frontend', 'backend', 'database', 'tools', 'language'], required: true }, icon: String, displayOrder: { type: Number, default: 0 }, visible: { type: Boolean, default: true } }, options));
export const Experience = model<IExperience>('Experience', new Schema<IExperience>({ company: { type: String, required: true }, role: { type: String, required: true }, companyLogo: String, companyLogoPublicId: String, startDate: { type: Date, required: true }, endDate: Date, current: { type: Boolean, default: false }, description: { type: String, required: true }, technologies: { type: [String], default: [] }, displayOrder: { type: Number, default: 0 } }, options));
export const Certificate = model<ICertificate>('Certificate', new Schema<ICertificate>({ name: { type: String, required: true }, issuer: { type: String, required: true }, issueDate: { type: Date, required: true }, image: String, imagePublicId: String, credentialId: String, credentialUrl: String, displayOrder: { type: Number, default: 0 } }, options));
const personalItemSchema = new Schema<IPersonalItem>({ category: { type: String, enum: ['hobbies', 'currently', 'favorites', 'dream-setup', 'dream-garage', 'dream-home', 'career-goal', 'life-goal', 'bucket-list', 'fun-facts', 'personal-quote'], required: true }, title: { type: String, required: true }, description: String, image: String, imagePublicId: String, imageAlt: String, label: String, icon: String, status: String, url: String, completed: { type: Boolean, default: false }, size: { type: String, enum: ['small', 'wide', 'tall', 'large'], required: true }, displayMode: { type: String, enum: ['visual', 'text'], default: 'text' }, order: { type: Number, default: 0 }, visible: { type: Boolean, default: true } }, options);
personalItemSchema.index({ category: 1, visible: 1, order: 1 });
export const PersonalItem = model<IPersonalItem>('PersonalItem', personalItemSchema);
export const SiteSettings = model<ISiteSettings>('SiteSettings', new Schema<ISiteSettings>({ siteTitle: { type: String, required: true }, terminalUsername: { type: String, required: true }, terminalHostname: { type: String, required: true }, systemOS: { type: String, required: true }, footerQuote: { type: String, required: true }, availabilityStatus: { type: String, required: true }, bootEnabled: { type: Boolean, default: true }, sideStreamEnabled: { type: Boolean, default: true }, crtEnabled: { type: Boolean, default: true } }, options));
export const Message = model<IMessage>('Message', new Schema<IMessage>({ name: { type: String, required: true }, email: { type: String, required: true }, message: { type: String, required: true }, read: { type: Boolean, default: false } }, options));
