import { randomBytes } from 'node:crypto';
import bcrypt from 'bcryptjs';
import { v2 as cloudinary } from 'cloudinary';
import request from 'supertest';
import { MongoMemoryServer } from 'mongodb-memory-server';
import { createApp } from '../src/app.js';
import { connectDatabase, disconnectDatabase } from '../src/config/db.js';
import type { ServerConfig } from '../src/config/env.js';
import { Admin } from '../src/models/index.js';

const origin = 'http://localhost:5173';
const password = randomBytes(24).toString('base64url');
async function test(): Promise<void> {
  const mongo = await MongoMemoryServer.create();
  try {
    const config: ServerConfig = { NODE_ENV: 'test', PORT: 3000, MONGODB_URI: mongo.getUri(), CLIENT_URL: origin, CLIENT_URLS: 'http://192.168.1.5:5173', AUTH_SECRET: randomBytes(48).toString('hex'), TRUST_PROXY: 0, COOKIE_SAME_SITE: 'lax' };
    await connectDatabase(config.MONGODB_URI);
    const app = createApp(config);
    const agent = request.agent(app);
    await Admin.create({ username: 'owner', passwordHash: await bcrypt.hash(password, 12) });
    await request(app).put('/api/manage/profile').set('Origin', origin).send({}).expect(401);
    const publicSession = await request(app).get('/api/auth/me').expect(200);
    if (publicSession.body.data.authenticated !== false || publicSession.headers['cache-control'] !== 'no-store') throw new Error('Anonymous session status should be false and uncached');
    await agent.post('/api/auth/login').set('Origin', origin).send({ password: 'incorrect' }).expect(401);
    const loggedIn = await agent.post('/api/auth/login').set('Origin', origin).send({ password }).expect(200);
    if (!String(loggedIn.headers['set-cookie']).includes('HttpOnly') || !String(loggedIn.headers['set-cookie']).includes('SameSite=Lax')) throw new Error('Session cookie missing security flags');
    if ((await agent.get('/api/auth/me').expect(200)).body.data.authenticated !== true) throw new Error('Authenticated session status should be true');
    await agent.put('/api/manage/profile').set('Origin', 'https://other.example').send({}).expect(403);
    const lanResponse = await request(app).get('/api/health').set('Origin', 'http://192.168.1.5:5173').expect(200);
    if (lanResponse.headers['access-control-allow-origin'] !== 'http://192.168.1.5:5173') throw new Error('LAN origin is not allowed by CORS');
    await request(app).post('/api/contact').set('Origin', 'http://192.168.1.5:5173').send({}).expect(400);
    const profile = { name: 'Davy', username: 'davy', role: 'Full-Stack Developer', location: 'Indonesia', status: 'Available', heroGreeting: "Hi, I'm", heroDescription: ['Building useful things.'], about: 'A developer bio.', profileImage: '', profileImagePublicId: '', email: 'davy@example.com', github: '', instagram: '', cvUrl: '', cvPublicId: '' };
    await agent.put('/api/manage/profile').set('Origin', origin).send(profile).expect(200);
    const publicProfile = await request(app).get('/api/profile').expect(200);
    if (publicProfile.body.data.name !== 'Davy') throw new Error('Profile write did not reach public API');
    const settings = { siteTitle: 'Portfolio OS', terminalUsername: 'davy', terminalHostname: 'portfolio', systemOS: 'portfolioOS', footerQuote: 'Ship thoughtfully.', availabilityStatus: 'Available', bootEnabled: true, sideStreamEnabled: true, crtEnabled: true };
    await agent.put('/api/manage/settings').set('Origin', origin).send(settings).expect(200);
    if ((await request(app).get('/api/settings').expect(200)).body.data.footerQuote !== 'Ship thoughtfully.') throw new Error('Settings did not update');
    const project = { name: 'Test Project', slug: 'test-project', shortDescription: 'An integration test project.', overview: '', problem: '', solution: '', challenges: '', result: '', features: ['Feature'], thumbnail: '', thumbnailPublicId: '', gallery: [], galleryPublicIds: [], stack: ['React'], status: 'development', githubUrl: '', liveUrl: '', featured: true, displayOrder: 2 };
    const created = await agent.post('/api/manage/projects').set('Origin', origin).send(project).expect(201);
    const projectId: string = created.body.data._id;
    const firstProjectId: string = (await agent.post('/api/manage/projects').set('Origin', origin).send({ ...project, slug: 'first-project', name: 'First Project', displayOrder: 0, featured: false }).expect(201)).body.data._id;
    if ((await request(app).get('/api/projects/test-project').expect(200)).body.data.name !== project.name) throw new Error('Project detail missing');
    await agent.put(`/api/manage/projects/${projectId}`).set('Origin', origin).send({ ...project, name: 'Updated Project' }).expect(200);
    const publicProjects = (await request(app).get('/api/projects').expect(200)).body.data;
    if (publicProjects[0].slug !== 'first-project' || publicProjects[1].name !== 'Updated Project' || !publicProjects[1].featured) throw new Error('Project order, feature flag, or update failed');
    await agent.post('/api/manage/projects').set('Origin', origin).send(project).expect(409);
    const skill = { name: 'React', category: 'frontend', icon: '', displayOrder: 1, visible: true };
    const skillId: string = (await agent.post('/api/manage/skills').set('Origin', origin).send(skill).expect(201)).body.data._id;
    await agent.put(`/api/manage/skills/${skillId}`).set('Origin', origin).send({ ...skill, name: 'TypeScript' }).expect(200);
    if ((await request(app).get('/api/skills').expect(200)).body.data[0].name !== 'TypeScript') throw new Error('Skill update not public');
    const experience = { company: 'Studio', role: 'Developer', startDate: '2025-01-01', current: true, description: 'Built interfaces.', technologies: ['React'], displayOrder: 1, companyLogo: '', companyLogoPublicId: '' };
    const experienceId: string = (await agent.post('/api/manage/experience').set('Origin', origin).send(experience).expect(201)).body.data._id;
    await agent.put(`/api/manage/experience/${experienceId}`).set('Origin', origin).send({ ...experience, role: 'Senior Developer' }).expect(200);
    if ((await request(app).get('/api/experience').expect(200)).body.data[0].role !== 'Senior Developer') throw new Error('Experience update not public');
    const certificate = { name: 'Certificate', issuer: 'Issuer', issueDate: '2026-01-01', image: '', imagePublicId: '', credentialId: '', credentialUrl: '', displayOrder: 0 };
    const certificateId: string = (await agent.post('/api/manage/certificates').set('Origin', origin).send(certificate).expect(201)).body.data._id;
    await agent.put(`/api/manage/certificates/${certificateId}`).set('Origin', origin).send({ ...certificate, name: 'Updated Certificate' }).expect(200);
    if ((await request(app).get('/api/certificates').expect(200)).body.data[0].name !== 'Updated Certificate') throw new Error('Certificate update not public');
    await request(app).post('/api/contact').set('Origin', origin).send({ name: 'Visitor', email: 'visitor@example.com', message: 'Hello there.' }).expect(201);
    await request(app).post('/api/contact').set('Origin', origin).send({ name: '', email: 'not-email', message: '' }).expect(400);
    const messages = await agent.get('/api/manage/messages').expect(200);
    const messageId: string = messages.body.data[0]._id;
    await agent.patch(`/api/manage/messages/${messageId}/read`).set('Origin', origin).expect(200);
    if ((await agent.get('/api/manage/overview').expect(200)).body.data.unread !== 0) throw new Error('Unread count not updated');
    await agent.delete(`/api/manage/messages/${messageId}`).set('Origin', origin).expect(200);
    await agent.post('/api/manage/uploads').set('Origin', origin).field('kind', 'image').attach('file', Buffer.from('not an image'), { filename: 'bad.png', contentType: 'image/png' }).expect(400);
    await agent.post('/api/manage/uploads').set('Origin', origin).field('kind', 'image').attach('file', Buffer.from('89504e470d0a1a0a0000000d49484452', 'hex'), { filename: 'valid.png', contentType: 'image/png' }).expect(503);
    await agent.post('/api/manage/uploads/sign').set('Origin', origin).send({ kind: 'image' }).expect(503);
    config.CLOUDINARY_CLOUD_NAME = 'test-cloud';
    config.CLOUDINARY_API_KEY = 'test-key';
    config.CLOUDINARY_API_SECRET = 'test-secret';
    const uploadSignature = (await agent.post('/api/manage/uploads/sign').set('Origin', origin).send({ kind: 'cv' }).expect(200)).body.data;
    const expectedSignature = cloudinary.utils.api_sign_request({ timestamp: uploadSignature.timestamp, folder: 'portfolio-os/cv', allowed_formats: 'pdf', overwrite: false }, 'test-secret');
    if (uploadSignature.signature !== expectedSignature || uploadSignature.resourceType !== 'raw' || uploadSignature.allowedFormats !== 'pdf') throw new Error('Browser upload signature is invalid');
    await agent.delete(`/api/manage/projects/${projectId}`).set('Origin', origin).expect(200);
    await agent.delete(`/api/manage/projects/${firstProjectId}`).set('Origin', origin).expect(200);
    await agent.delete(`/api/manage/skills/${skillId}`).set('Origin', origin).expect(200);
    await agent.delete(`/api/manage/experience/${experienceId}`).set('Origin', origin).expect(200);
    await agent.delete(`/api/manage/certificates/${certificateId}`).set('Origin', origin).expect(200);
    await agent.post('/api/auth/logout').set('Origin', origin).expect(200);
    if ((await agent.get('/api/auth/me').expect(200)).body.data.authenticated !== false) throw new Error('Logout should clear session status');
    await agent.get('/api/manage/messages').expect(401);
    console.info('Integration passed: auth, protected CRUD, public reads, contact, validation, uploads rejection, and logout.');
  } finally { await disconnectDatabase(); await mongo.stop(); }
}
test().catch(error => { console.error(error); process.exitCode = 1; });
